{{- if not .Values.xeolAgent.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "xeol-agent.fullname" . }}
  labels:
    app: {{ template "xeol-agent.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- with .Values.xeolAgent.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  XEOL_AGENT_XEOL_API_KEY: {{  .Values.xeolAgent.xeol.apiKey }}
{{- end }}
